MODEL (
  name s3depot.device_08.system_update_report,
  grain _id,
  kind FULL,
  description 'Cleaned CDC data with deduplication logic for system update report',
  physical_properties (
    format = 'iceberg'
  ),
  columns (
    _id STRING,
    scan_id STRING,
    org_id STRING,
    device_id STRING,
    package_id STRING,
    installation_status STRING,
    coreq_package_id STRING,
    package_name STRING,
    package_description STRING,
    package_version STRING,
    current_installed_version STRING,
    package_release_date STRING,
    package_vendor STRING,
    package_type STRING,
    package_severity STRING,
    package_reboot_type STRING,
    package_size STRING,
    disk_space_required STRING,
    package_tips STRING,
    readme_url STRING,
    license_url STRING,
    device_display_name STRING,
    device_serial_number STRING,
    device_product_name STRING,
    created_at TIMESTAMP,
    last_modified_date TIMESTAMP,
    device_local_event_date_time TIMESTAMP,
    event_date_time TIMESTAMP,
    filtering_group_name STRING,
    failure_reason STRING,
    _nilus_load_id TIMESTAMP,
    _nilus_id STRING
  ),
  column_descriptions (
    _id = 'Unique system update report record identifier and model grain.',
    scan_id = 'Scan identifier for the update deployment run.',
    org_id = 'Organization identifier for the deployment.',
    device_id = 'Business device identifier for the deployment target.',
    package_id = 'Update package identifier deployed or attempted.',
    installation_status = 'Outcome of the update deployment (DEPLOYED, FAILED, PENDING, etc.).',
    coreq_package_id = 'Co-requisite package identifier required with this update.',
    package_name = 'Display name of the update package.',
    package_description = 'Description of the update package.',
    package_version = 'Version of the update package.',
    current_installed_version = 'Version currently installed on the device.',
    package_release_date = 'Timestamp when the package was released.',
    package_vendor = 'Vendor that published the update package.',
    package_type = 'Type of update package (Driver, Firmware, Application, etc.).',
    package_severity = 'Severity level of the update package (CRITICAL, RECOMMENDED, OPTIONAL).',
    package_reboot_type = 'Reboot behavior required to apply the package.',
    package_size = 'Reported size of the update package.',
    disk_space_required = 'Disk space required to install the package.',
    package_tips = 'Installation tips provided for the package.',
    readme_url = 'URL to the package readme documentation.',
    license_url = 'URL to the package license documentation.',
    device_display_name = 'Display name of the target device.',
    device_serial_number = 'Serial number of the target device.',
    device_product_name = 'Product name of the target device.',
    created_at = 'Timestamp when the report record was created.',
    last_modified_date = 'Timestamp when the report record was last modified.',
    device_local_event_date_time = 'Event timestamp in the device local time zone.',
    event_date_time = 'Event timestamp in normalized form.',
    filtering_group_name = 'Filtering group name applied to the deployment.',
    failure_reason = 'Reason recorded when the deployment failed.',
    _nilus_load_id = 'Ingestion load identifier assigned by Nilus.',
    _nilus_id = 'Ingestion record identifier assigned by Nilus.'
  ),
  column_tags (
    _id = ('identifier', 'primary_key', 'grain', 'system-update'),
    scan_id = ('identifier', 'system-update', 'scan'),
    org_id = ('identifier', 'organization', 'system-update'),
    device_id = ('identifier', 'device', 'system-update'),
    package_id = ('identifier', 'system-update', 'package'),
    installation_status = ('status', 'system-update', 'deployment'),
    coreq_package_id = ('identifier', 'system-update', 'corequisite'),
    package_name = ('dimension', 'system-update', 'package-name'),
    package_description = ('dimension', 'system-update', 'description'),
    package_version = ('dimension', 'system-update', 'version'),
    current_installed_version = ('dimension', 'system-update', 'installed-version'),
    package_release_date = ('timestamp', 'system-update', 'release-date'),
    package_vendor = ('dimension', 'system-update', 'vendor'),
    package_type = ('classification', 'system-update', 'type'),
    package_severity = ('classification', 'system-update', 'severity'),
    package_reboot_type = ('classification', 'system-update', 'reboot'),
    package_size = ('measure', 'system-update', 'size'),
    disk_space_required = ('measure', 'system-update', 'disk-space'),
    package_tips = ('dimension', 'system-update', 'tips'),
    readme_url = ('identifier', 'system-update', 'readme'),
    license_url = ('identifier', 'system-update', 'license'),
    device_display_name = ('dimension', 'device', 'display-name'),
    device_serial_number = ('identifier', 'device', 'serial-number'),
    device_product_name = ('dimension', 'device', 'product-name'),
    created_at = ('timestamp', 'system-update', 'created_at'),
    last_modified_date = ('timestamp', 'system-update', 'updated_at'),
    device_local_event_date_time = ('timestamp', 'system-update', 'local-event'),
    event_date_time = ('timestamp', 'system-update', 'event'),
    filtering_group_name = ('dimension', 'system-update', 'filtering-group'),
    failure_reason = ('dimension', 'system-update', 'failure'),
    _nilus_load_id = ('metadata', 'ingestion', 'load_id'),
    _nilus_id = ('metadata', 'ingestion', 'record_id')
  ),
  column_terms (
    _id = ('system_update_report.record_id', 'identity.primary_key'),
    scan_id = ('system_update_report.scan_id', 'patch.scan_id'),
    org_id = ('system_update_report.organization_id', 'organization.identifier'),
    device_id = ('system_update_report.device_id', 'device.identifier'),
    package_id = ('system_update_report.package_id', 'patch.package_id'),
    installation_status = ('system_update_report.installation_status', 'patch.deployment_outcome'),
    coreq_package_id = ('system_update_report.coreq_package_id', 'patch.corequisite_id'),
    package_name = ('system_update_report.package_name', 'patch.package_name'),
    package_description = ('system_update_report.package_description', 'patch.description'),
    package_version = ('system_update_report.package_version', 'patch.version'),
    current_installed_version = ('system_update_report.current_installed_version', 'patch.installed_version'),
    package_release_date = ('system_update_report.package_release_date', 'patch.release_date'),
    package_vendor = ('system_update_report.package_vendor', 'patch.vendor'),
    package_type = ('system_update_report.package_type', 'patch.update_type'),
    package_severity = ('system_update_report.package_severity', 'patch.severity_level'),
    package_reboot_type = ('system_update_report.package_reboot_type', 'patch.reboot_type'),
    package_size = ('system_update_report.package_size', 'patch.size'),
    disk_space_required = ('system_update_report.disk_space_required', 'patch.disk_space'),
    package_tips = ('system_update_report.package_tips', 'patch.tips'),
    readme_url = ('system_update_report.readme_url', 'patch.readme_url'),
    license_url = ('system_update_report.license_url', 'patch.license_url'),
    device_display_name = ('system_update_report.device_display_name', 'device.display_name'),
    device_serial_number = ('system_update_report.device_serial_number', 'identity.serial_number'),
    device_product_name = ('system_update_report.device_product_name', 'device.product_name'),
    created_at = ('system_update_report.created_at', 'record.created_at'),
    last_modified_date = ('system_update_report.last_modified_date', 'record.updated_at'),
    device_local_event_date_time = ('system_update_report.device_local_event_date_time', 'patch.local_event_time'),
    event_date_time = ('system_update_report.event_date_time', 'patch.event_time'),
    filtering_group_name = ('system_update_report.filtering_group_name', 'patch.filtering_group'),
    failure_reason = ('system_update_report.failure_reason', 'patch.failure_reason'),
    _nilus_load_id = ('system_update_report.load_id', 'ingestion.load_id'),
    _nilus_id = ('system_update_report.nilus_id', 'ingestion.record_id')
  ),
  profiles (
    _id,
    scan_id,
    org_id,
    device_id,
    package_id,
    installation_status,
    coreq_package_id,
    package_name,
    package_description,
    package_version,
    current_installed_version,
    package_release_date,
    package_vendor,
    package_type,
    package_severity,
    package_reboot_type,
    package_size,
    disk_space_required,
    package_tips,
    readme_url,
    license_url,
    device_display_name,
    device_serial_number,
    device_product_name,
    created_at,
    last_modified_date,
    device_local_event_date_time,
    event_date_time,
    filtering_group_name,
    failure_reason,
    _nilus_load_id,
    _nilus_id
  )
);


-- CREATE OR REPLACE TEMP VIEW _temp_view_consumed_licenses_cdc
-- USING json
-- OPTIONS (
--   'path' 's3a://warehouse/lenovo/01-14-2026-14-32-42_files_list/consumed_licenses_cdc.json',
--   'multiline' 'true'
-- );


-- CREATE OR REPLACE TEMP VIEW _temp_view_consumed_licenses_full
-- USING json
-- OPTIONS (
--   'path' 's3a://warehouse/lenovo/01-14-2026-14-32-42_files_list/consumed_licenses_full.json',
--   'multiline' 'true'
-- );

SELECT
   _id,
   scan_id,
   org_id,
   device_id,
   package_id,
   installation_status,
   coreq_package_id,
   package_name,
   package_description,
   package_version,
   current_installed_version,
   cast(package_release_date as timestamp) as package_release_date,
   package_vendor,
   package_type,
   package_severity,
   package_reboot_type,
   package_size,
   disk_space_required,
   package_tips,
   readme_url,
   license_url,
   device_display_name,
   device_serial_number,
   device_product_name,
   cast(created_at as timestamp) as created_at,
   cast(last_modified_date as timestamp) as last_modified_date,
   cast(device_local_event_date_time as timestamp) as device_local_event_date_time,
   cast(event_date_time as timestamp) as event_date_time,
   filtering_group_name,
   failure_reason,
   to_timestamp(from_unixtime(CAST(_nilus_load_id AS DOUBLE))) AS _nilus_load_id,
   _nilus_id
FROM (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY _id
            ORDER BY CAST(_nilus_load_id AS BIGINT) DESC
        ) AS rn
    FROM s3depot.demolake04.system_update_report
)
WHERE rn = 1
