name: devicecadpsri
display_name: Device Orch 360 Consumer Aligned Data Product (CADP)
description: "Device Orch 360 Consumer Aligned Data Product (CADP)"
discoverable: true
version: 0.0.1
# domain: LDO
alignment: consumer_aligned
model_defaults:
  dialect: trino
ignore_patterns:
  - "deploy.yml"  
tags:
  - trino
  - device-360-trino
  - device-360-usecases
  - device-insights-360

terms:
  - glossary.data_product
  - device-insights-trino
  - device-insights-usecases
gateways:
  default:
    connection:
      type: trino
      host: "tcp.lnv-051826.dataos.cloud"
      port: 7432
      user: "sgali1_lenovocomextrubikdatasolutionsonmicrosoftcom"
      catalog: "s3depot"
      http_scheme: https
      method: basic
      #password: ""
      password: "{{ env_var('TRINO_PASSWORD', '') }}"
      verify: true
#     state_connection:
#       type: duckdb
#       database: ./statestore.duckdb
# transpiler:
#   base_url: "https://lnv-051826.dataos.cloud/transpiler"
#   timeout: 100
#   token: 

users:
  - username: sgali1_lenovocomextrubikdatasolutionsonmicrosoftcom
    email: sgali1@lenovo.com
    type: OWNER

 