MODEL (
  name s3depot.device_08.devices,
  grain id,    
  cron '*/30 * * * *',
  kind FULL,
  description 'Latest deduplicated device inventory records for device orchestration, including device identity, lifecycle flags, and registration attributes.',
  tags ('source-aligned', 'device-insights-360', 'devices', 'cdc'),
  terms ('device_orch.devices', 'device_orch_360.device_inventory', 'device.master'),
  physical_properties (
    format = 'iceberg'
  ),
  columns (
    id STRING,
    device_id STRING,
    org_id STRING,
    serial_number STRING,
    model_type STRING,
    family STRING,
    manufacturer STRING,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active BOOLEAN,
    category STRING,
    model_name STRING,
    trust_anchor STRING,
    platform STRING,
    org_device_id STRING,
    subscription_id STRING,
    device_category STRING,
    name STRING,
    _nilus_load_id STRING,
    _nilus_id STRING,
    status STRING,
    registration_type STRING
  ),
  column_descriptions (
    id = 'Unique device record identifier and model grain.',
    device_id = 'Business device identifier from the source system.',
    org_id = 'Organization identifier that owns the device.',
    serial_number = 'Serial number reported for the device.',
    model_type = 'Model type reported for the device.',
    family = 'Device family classification.',
    manufacturer = 'Manufacturer of the device.',
    created_at = 'Timestamp when the device record was created.',
    updated_at = 'Timestamp when the device record was last updated.',
    is_active = 'Flag indicating whether the device is currently active.',
    category = 'Raw device category reported by the source system.',
    model_name = 'Model name reported for the device.',
    trust_anchor = 'Trust anchor associated with the device identity.',
    platform = 'Operating platform associated with the device.',
    org_device_id = 'Organization-scoped device identifier.',
    subscription_id = 'Subscription identifier associated with the device.',
    device_category = 'Normalized high-level device category derived from the raw category.',
    name = 'Display name of the device.',
    _nilus_load_id = 'Ingestion load identifier assigned by Nilus.',
    _nilus_id = 'Ingestion record identifier assigned by Nilus.',
    status = 'Device status value reserved by the source-aligned model.',
    registration_type = 'Registration type associated with the device.'
  ),
  column_tags (
    id = ('identifier', 'primary_key', 'grain', 'device'),
    device_id = ('identifier', 'device', 'business-key'),
    org_id = ('identifier', 'organization', 'device'),
    serial_number = ('identifier', 'device', 'serial-number'),
    model_type = ('classification', 'device', 'model-type'),
    family = ('classification', 'device', 'family'),
    manufacturer = ('dimension', 'device', 'manufacturer'),
    created_at = ('timestamp', 'device', 'created_at'),
    updated_at = ('timestamp', 'device', 'updated_at'),
    is_active = ('indicator', 'device', 'active'),
    category = ('classification', 'device', 'category'),
    model_name = ('dimension', 'device', 'model-name'),
    trust_anchor = ('identifier', 'device', 'trust-anchor'),
    platform = ('classification', 'device', 'platform'),
    org_device_id = ('identifier', 'device', 'organization-key'),
    subscription_id = ('identifier', 'subscription', 'device'),
    device_category = ('classification', 'device', 'normalized-category'),
    name = ('dimension', 'device', 'display-name'),
    _nilus_load_id = ('metadata', 'ingestion', 'load_id'),
    _nilus_id = ('metadata', 'ingestion', 'record_id'),
    status = ('status', 'device', 'lifecycle'),
    registration_type = ('classification', 'device', 'registration')
  ),
  column_terms (
    id = ('devices.record_id', 'identity.primary_key'),
    device_id = ('devices.device_id', 'device.identifier'),
    org_id = ('devices.organization_id', 'organization.identifier'),
    serial_number = ('devices.serial_number', 'identity.serial_number'),
    model_type = ('devices.model_type', 'device.model_type'),
    family = ('devices.family', 'device.family'),
    manufacturer = ('devices.manufacturer', 'device.manufacturer'),
    created_at = ('devices.created_at', 'record.created_at'),
    updated_at = ('devices.updated_at', 'record.updated_at'),
    is_active = ('devices.is_active', 'device.active_flag'),
    category = ('devices.raw_category', 'device.category'),
    model_name = ('devices.model_name', 'device.model_name'),
    trust_anchor = ('devices.trust_anchor', 'device.trust_anchor'),
    platform = ('devices.platform', 'device.platform'),
    org_device_id = ('devices.org_device_id', 'device.organization_device_id'),
    subscription_id = ('devices.subscription_id', 'subscription.identifier'),
    device_category = ('devices.normalized_category', 'device.category_normalized'),
    name = ('devices.device_name', 'device.display_name'),
    _nilus_load_id = ('devices.load_id', 'ingestion.load_id'),
    _nilus_id = ('devices.nilus_id', 'ingestion.record_id'),
    status = ('devices.status', 'device.status'),
    registration_type = ('devices.registration_type', 'device.registration_type')
  ),
  profiles (
    id,
    device_id,
    org_id,
    serial_number,
    model_type,
    family,
    manufacturer,
    created_at,
    updated_at,
    is_active,
    category,
    model_name,
    trust_anchor,
    platform,
    org_device_id,
    subscription_id,
    device_category,
    name,
    _nilus_load_id,
    _nilus_id,
    status,
    registration_type
  )
);

SELECT
    id,
    device_id,
    org_id,
    serial_number,
    model_type,
    family,
    manufacturer,
    CAST(from_unixtime(CAST(created_at AS BIGINT) / 1000000) AS TIMESTAMP) as created_at,
    CAST(from_unixtime(CAST(updated_at AS BIGINT) / 1000000) AS TIMESTAMP) as updated_at,
    is_active,
    category,
    model_name,
    trust_anchor,
    platform,
    org_device_id,
    subscription_id,
    CASE 
        WHEN upper(category) = 'PC' THEN 'PC'
        WHEN upper(category) IN ('MOBILE', 'PHONE', 'TABLET') THEN 'Mobile/Tablet'
        WHEN upper(category) = 'SMARTEDGE' THEN 'SmartEdge'
        WHEN upper(category) IN ('AR', 'VR') THEN 'AR/VR'
        WHEN upper(category) = 'CHROMEBOOK' THEN 'Chromebook'
        WHEN upper(category) = 'OTHER' THEN NULL
        ELSE 'Other'
    END as device_category,
    name,
    _nilus_load_id,
    _nilus_id,
    CAST(null AS STRING) as status,
    registration_type
FROM (
    SELECT
        id,
        device_id,
        org_id,
        serial_number,
        model_type,
        family,
        manufacturer,
        created_at,
        updated_at,
        is_active,
        category,
        model_name,
        trust_anchor,
        platform,
        org_device_id,
        subscription_id,
        name,
        _nilus_load_id,
        _nilus_id,
        registration_type,
        ROW_NUMBER() OVER (
            PARTITION BY id
            ORDER BY CAST(_nilus_load_id AS BIGINT) DESC
        ) AS rn
    FROM s3depot.demolake04.devices
)
WHERE rn = 1;

