name: devicesadppari
display_name: Pari's Device Orch 360 Source Aligned Data Product
description: "Pari's Device Orch 360 Source Aligned Data Product"
discoverable: true
version: 0.0.1
domain: LDO
alignment: source_aligned
model_defaults:
  dialect: spark2
  start: '2026-01-01'
  cron: '*/30 * * * *'
tags:
  - spark
  - device-360-sadp
  - device-360-usecases
  - device-insights-360

terms:
  - glossary.data_product
  - device-insights-360
  - device-insights-usecases
linter:
  enabled: false
  # warn_rules:
  #   - preferassertions
  #   - nomissingaudits

gateways:
  default:
    connection:
      type: depot
      address: dataos://s3depot
      # config:
      #   spark.dynamicAllocation.enabled: "true"
      #   spark.dynamicAllocation.shuffleTracking.enabled: "true"
      #   spark.dynamicAllocation.initialExecutors: "1"
      #   spark.dynamicAllocation.minExecutors: "1"
      #   spark.dynamicAllocation.maxExecutors: "2"
 


users:
  - username: prajarathina_lenovocomextrubikdatasolutionsonmicrosoftcom
    email: prajarathina_lenovo.com#ext#@rubikdatasolutions.onmicrosoft.com
    type: OWNER