MODEL (
  name s3depot.device_cadp.devices,
  kind VIEW,
  grain id,
  description 'View on Spark processed devices data',
  columns (
    id VARCHAR,
    device_id VARCHAR,
    org_id VARCHAR,
    serial_number VARCHAR,
    model_type VARCHAR,
    family VARCHAR,
    manufacturer VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active BOOLEAN,
    category VARCHAR,
    model_name VARCHAR,
    trust_anchor VARCHAR,
    platform VARCHAR,
    org_device_id VARCHAR,
    subscription_id VARCHAR,
    device_category VARCHAR,
    name VARCHAR,
    _nilus_load_id VARCHAR,
    _nilus_id VARCHAR,
    status VARCHAR
    -- registration_type VARCHAR
  ),
  column_descriptions (
    id = 'Unique device record identifier and model grain.',
    device_id = 'Business device identifier from the source system.',
    org_id = 'Organization identifier that owns the device.',
    serial_number = 'Serial number reported for the device.',
    model_type = 'Model type reported for the device.',
    family = 'Device family classification.',
    manufacturer = 'Manufacturer of the device.',
    created_at = 'Timestamp when the device record was created.',
    updated_at = 'Timestamp when the device record was last updated.',
    is_active = 'Flag indicating whether the device is currently active.',
    category = 'Raw device category reported by the source system.',
    model_name = 'Model name reported for the device.',
    trust_anchor = 'Trust anchor associated with the device identity.',
    platform = 'Operating platform associated with the device.',
    org_device_id = 'Organization-scoped device identifier.',
    subscription_id = 'Subscription identifier associated with the device.',
    device_category = 'Normalized high-level device category derived from the raw category.',
    name = 'Display name of the device.',
    _nilus_load_id = 'Ingestion load identifier assigned by Nilus.',
    _nilus_id = 'Ingestion record identifier assigned by Nilus.',
    status = 'Device status value reserved by the source-aligned model.'
    -- registration_type = 'Registration type associated with the device.'
  ),
  column_tags (
    id = ('identifier', 'primary_key', 'grain', 'device'),
    device_id = ('identifier', 'device', 'business-key'),
    org_id = ('identifier', 'organization', 'device'),
    serial_number = ('identifier', 'device', 'serial-number'),
    model_type = ('classification', 'device', 'model-type'),
    family = ('classification', 'device', 'family'),
    manufacturer = ('dimension', 'device', 'manufacturer'),
    created_at = ('timestamp', 'device', 'created_at'),
    updated_at = ('timestamp', 'device', 'updated_at'),
    is_active = ('indicator', 'device', 'active'),
    category = ('classification', 'device', 'category'),
    model_name = ('dimension', 'device', 'model-name'),
    trust_anchor = ('identifier', 'device', 'trust-anchor'),
    platform = ('classification', 'device', 'platform'),
    org_device_id = ('identifier', 'device', 'organization-key'),
    subscription_id = ('identifier', 'subscription', 'device'),
    device_category = ('classification', 'device', 'normalized-category'),
    name = ('dimension', 'device', 'display-name'),
    _nilus_load_id = ('metadata', 'ingestion', 'load_id'),
    _nilus_id = ('metadata', 'ingestion', 'record_id'),
    status = ('status', 'device', 'lifecycle')
    -- registration_type = ('classification', 'device', 'registration')
  ),
  column_terms (
    id = ('devices.record_id', 'identity.primary_key'),
    device_id = ('devices.device_id', 'device.identifier'),
    org_id = ('devices.organization_id', 'organization.identifier'),
    serial_number = ('devices.serial_number', 'identity.serial_number'),
    model_type = ('devices.model_type', 'device.model_type'),
    family = ('devices.family', 'device.family'),
    manufacturer = ('devices.manufacturer', 'device.manufacturer'),
    created_at = ('devices.created_at', 'record.created_at'),
    updated_at = ('devices.updated_at', 'record.updated_at'),
    is_active = ('devices.is_active', 'device.active_flag'),
    category = ('devices.raw_category', 'device.category'),
    model_name = ('devices.model_name', 'device.model_name'),
    trust_anchor = ('devices.trust_anchor', 'device.trust_anchor'),
    platform = ('devices.platform', 'device.platform'),
    org_device_id = ('devices.org_device_id', 'device.organization_device_id'),
    subscription_id = ('devices.subscription_id', 'subscription.identifier'),
    device_category = ('devices.normalized_category', 'device.category_normalized'),
    name = ('devices.device_name', 'device.display_name'),
    _nilus_load_id = ('devices.load_id', 'ingestion.load_id'),
    _nilus_id = ('devices.nilus_id', 'ingestion.record_id'),
    status = ('devices.status', 'device.status')
    -- registration_type = ('devices.registration_type', 'device.registration_type')
  )
);

SELECT
  *
FROM s3depot.device_meb.devices
