MODEL (
  name s3depot.device_cadp.issues,
  kind VIEW,
  grain issue_uuid,
  description 'View on Spark processed issues data',
  columns (
    issue_uuid VARCHAR,
    bucket_id VARCHAR,
    category VARCHAR,
    hardware_id VARCHAR,
    reported_at TIMESTAMP,
    resolved_at TIMESTAMP,
    status VARCHAR,
    timeline VARCHAR,
    updated_at TIMESTAMP,
    value VARCHAR,
    device_id VARCHAR,
    insight_id VARCHAR,
    generate_ticket BOOLEAN,
    has_ticket BOOLEAN,
    is_hidden BOOLEAN,
    insight_item_id VARCHAR,
    _nilus_load_id TIMESTAMP,
    _nilus_id VARCHAR,
    battery_id VARCHAR,
    predicted_to_occur_on TIMESTAMP,
    code VARCHAR,
    s_id VARCHAR,
    details VARCHAR,
    avg_cpu_usage DOUBLE
  ),
  column_descriptions (
    issue_uuid = 'Unique issue record identifier and model grain.',
    bucket_id = 'Bucket identifier grouping related issues.',
    category = 'Issue category classification from the source system.',
    hardware_id = 'Hardware component identifier associated with the issue.',
    reported_at = 'Timestamp when the issue was first reported.',
    resolved_at = 'Timestamp when the issue was resolved, if applicable.',
    status = 'Current lifecycle status of the issue (open, resolved, etc.).',
    timeline = 'Serialized timeline of issue state transitions.',
    updated_at = 'Timestamp when the issue record was last updated.',
    value = 'Raw metric or diagnostic value associated with the issue.',
    device_id = 'Business device identifier associated with the issue.',
    insight_id = 'Insight rule identifier that generated the issue.',
    generate_ticket = 'Flag indicating whether a support ticket should be generated.',
    has_ticket = 'Flag indicating whether a support ticket exists for the issue.',
    is_hidden = 'Flag indicating whether the issue is hidden from default views.',
    insight_item_id = 'Identifier of the specific insight item within the rule.',
    _nilus_load_id = 'Ingestion load identifier assigned by Nilus.',
    _nilus_id = 'Ingestion record identifier assigned by Nilus.',
    battery_id = 'Battery identifier when the issue is battery-related.',
    predicted_to_occur_on = 'Timestamp when the issue is predicted to occur.',
    code = 'Issue diagnostic code from the source system.',
    s_id = 'Secondary source identifier for the issue.',
    details = 'Free-text details describing the issue.',
    avg_cpu_usage = 'Average CPU usage derived for app performance impact insights.'
  ),
  column_tags (
    issue_uuid = ('identifier', 'primary_key', 'grain', 'issues'),
    bucket_id = ('identifier', 'issues', 'bucket'),
    category = ('classification', 'issues', 'category'),
    hardware_id = ('identifier', 'issues', 'hardware'),
    reported_at = ('timestamp', 'issues', 'reported_at'),
    resolved_at = ('timestamp', 'issues', 'resolved_at'),
    status = ('status', 'issues', 'lifecycle'),
    timeline = ('dimension', 'issues', 'timeline'),
    updated_at = ('timestamp', 'issues', 'updated_at'),
    value = ('measure', 'issues', 'value'),
    device_id = ('identifier', 'device', 'issues'),
    insight_id = ('identifier', 'issues', 'insight'),
    generate_ticket = ('indicator', 'issues', 'ticket'),
    has_ticket = ('indicator', 'issues', 'ticket'),
    is_hidden = ('indicator', 'issues', 'visibility'),
    insight_item_id = ('identifier', 'issues', 'insight-item'),
    _nilus_load_id = ('metadata', 'ingestion', 'load_id'),
    _nilus_id = ('metadata', 'ingestion', 'record_id'),
    battery_id = ('identifier', 'battery', 'issues'),
    predicted_to_occur_on = ('timestamp', 'issues', 'prediction'),
    code = ('identifier', 'issues', 'code'),
    s_id = ('identifier', 'issues', 'source-id'),
    details = ('dimension', 'issues', 'details'),
    avg_cpu_usage = ('measure', 'issues', 'cpu-usage')
  ),
  column_terms (
    issue_uuid = ('issues.record_id', 'identity.primary_key'),
    bucket_id = ('issues.bucket_id', 'issue.bucket_id'),
    category = ('issues.category', 'issue.category'),
    hardware_id = ('issues.hardware_id', 'issue.hardware_id'),
    reported_at = ('issues.reported_at', 'issue.reported_at'),
    resolved_at = ('issues.resolved_at', 'issue.resolved_at'),
    status = ('issues.status', 'health.issue_state'),
    timeline = ('issues.timeline', 'issue.timeline'),
    updated_at = ('issues.updated_at', 'record.updated_at'),
    value = ('issues.value', 'issue.value'),
    device_id = ('issues.device_id', 'device.identifier'),
    insight_id = ('issues.insight_id', 'issue.insight_id'),
    generate_ticket = ('issues.generate_ticket', 'issue.generate_ticket'),
    has_ticket = ('issues.has_ticket', 'issue.has_ticket'),
    is_hidden = ('issues.is_hidden', 'issue.hidden'),
    insight_item_id = ('issues.insight_item_id', 'issue.insight_item_id'),
    _nilus_load_id = ('issues.load_id', 'ingestion.load_id'),
    _nilus_id = ('issues.nilus_id', 'ingestion.record_id'),
    battery_id = ('issues.battery_id', 'battery.identifier'),
    predicted_to_occur_on = ('issues.predicted_to_occur_on', 'issue.predicted_date'),
    code = ('issues.code', 'issue.code'),
    s_id = ('issues.s_id', 'issue.source_id'),
    details = ('issues.details', 'issue.details'),
    avg_cpu_usage = ('issues.avg_cpu_usage', 'issue.cpu_usage')
  )
);

SELECT
  *
FROM s3depot.device_08.issues
